services:
  postgres:
    image: ankane/pgvector:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: database_trial
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - fin-agent-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  agent_backend:
    build: ./agent_backend
    environment:
      - PORT=4000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "4000:4000"    
    volumes:
      - ./agent_backend:/app      
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - fin-agent-network
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_URL=http://agent_backend:4000
    networks:
      - fin-agent-network
    depends_on:
      - agent_backend
    restart: unless-stopped

networks:
  fin-agent-network:
    driver: bridge

volumes:
  postgres_data: